dev: 
  - envs/dev/**
  - modules/**
  - providers/**
  - service-registration/**
  - stacks/**
  - .opentofu-version
  - .terragrunt-version
  - .github/workflows/cicd.yaml
  - root.hcl
dev-dan: 'envs/dev-dan/**'
dev-sj11: 'envs/dev-sj11/**'
qa: 'envs/qa/**'
demo: 'envs/demo/**'
prod: 'envs/prod/**'