name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Get GH token from Github App
        id: gh-app-auth
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.NOTIFYCAL_CICD_APP_ID }}
          private_key: ${{ secrets.NOTIFYCAL_CICD_APP_SECRET }}

      - name: Hack for github internal repo access :(
        run: git config --global url."https://foo:${{ steps.gh-app-auth.outputs.token }}@github.com".insteadOf ssh://git@github.com
  
      - name: Install tenv
        run: |
          mkdir -p ~/.tenv && cd ~/.tenv
          wget -nv https://github.com/tofuutils/tenv/releases/download/${TENV_VERSION}/tenv_${TENV_VERSION}_${TENV_ARCH}.tar.gz -O tenv.tar.gz
          tar zxf tenv.tar.gz
          rm -rf tenv.tar.gz
          echo "$HOME/.tenv" >> "$GITHUB_PATH"
        env:
          TENV_VERSION: v1.7.1
          TENV_ARCH: Linux_x86_64

      - name: Install OpenTofu and Terragrunt
        run: |
          tenv tofu install
          tenv tg install

          terragrunt --version
          tofu --version

      # TODO: AWS Auth
      
      - name: Run against dev
        run: |
          cd envs/dev
          terragrunt run-all init
      # - run: terragrunt run-all plan
          
